### ISSUE TITLE
Input is shadowed in the --proto_path

### ISSUE THREAD

**Issue by nvartolomei** [thesamet/sbt-protoc#12]
> [error] `proto/svc1/rpc.proto`: Input is shadowed in the --proto_path by `proto/svc2/rpc.proto`.  Either use the latter file as your input or reorder the --proto_path so that the former file's location comes first.

We store every protobuf in a single repository, because some services require only few of them I decided to import them like so:
```sbt
PB.protoSources in Compile := Seq(
  file("vendor/proto/svc1"),
  file("vendor/proto/svc2"),
)
```

And this fails with the error above. Any solutions for this?

The following is working correctly:
```sbt
PB.protoSources in Compile := Seq(
  file("vendor/proto/")
)
```

**Comment by thesamet** [comment]
This is beyond sbt-protoc, the error you are seeing comes from protoc. The issue is that given the search path you are setting `import rpc.proto` becomes ambiguous. If the two `rpc.proto` belong to different projects, maybe they can be put in a different subdirectory under each project and then the conflict wouldn't occur.
