### ISSUE TITLE
Sources dir included twice

### ISSUE THREAD

**Issue by teodor-pripoae** [thesamet/sbt-protoc#13]
We are using a `proto` repository shared between multiple applications and I need to vendor generated sources in each application repository.

My `build.sbt` file looks like this:

```
PB.protoSources in Compile := Seq(
  file("vendor/proto/changelog")
)
PB.deleteTargetDirectory := false
PB.targets in Compile := Seq(
  scalapb
    .gen(grpc = true, flatPackage = true) -> baseDirectory.value / "src" / "main" / "scala"
)
```

When I compile locally (where I have the vendor/proto submodule), I get this error:

```
Application.scala:10: Application is already defined as object Application
.....
```

I think `src/main/scala` gets added twice to sbt source file configuration. How can I fix this ?

**Comment by thesamet** [comment]
Can you put together a minimal example on github?

**Comment by teodor-pripoae** [comment]
Hi,

I've put 2 projects on github:

- https://github.com/teodor-pripoae/scalapb-example - This one is an example application which uses proto files from a common repository. The common proto repository is added as a submodule in `vendor/proto`. To initialize it you need to run `git submodule init` and `git submodule update`.
- https://github.com/teodor-pripoae/scalapb-example-proto - This one is the common proto repository.

- If I use the default aproach (managed sources) then I'm not able to compile the app without access to proto repository (on CI server, heroku, etc)
- If I use the aproach used right now, I can compile and vendor generated files in my code but source dirs are added twice.
- If I compile and then comment the code below everything works ok but I'm not able anymore to compile protobufs when they change:

```
PB.protoSources in Compile := Seq(
  file("vendor/proto/echo"),
  file("src/main/protobuf")
)
PB.deleteTargetDirectory := false
PB.targets in Compile := Seq(
  scalapb
    .gen(grpc = true, flatPackage = true) -> baseDirectory.value / "src/main/scala"
)
```

**Comment by thesamet** [comment]
The problem is that you are generating into `src/main/scala`. Every file that is generated into that directory will be compiled twice by SBT: one time because it was returned by a generator, and second time because it's inside `scalaSource`. The easiest solution for you would be to generate to another subdirectory of src/main:

```PB.targets in Compile := Seq(
  scalapb
    .gen(grpc = true, flatPackage = true) -> baseDirectory.value / "src/main/scala-protos"
)```

Other approaches (as I personally don't like to check in generated code):
- If you have access to the vendor repository - add ScalaPB there and publish a jar with the generated protos. 
- On CI, Heroku - maybe it's possible to execute arbitrary shell commands before the build, so the submodule can become available?
