### ISSUE TITLE
Support for gRPC Java classes generating

### ISSUE THREAD

**Issue by augi** [thesamet/sbt-protoc#64]
I'm aware of [this example](https://github.com/thesamet/sbt-protoc/blob/master/examples/grpc-java/build.sbt) and I'm just curious why this is not supported in the plugin directly.

I'm willing to implement the MR but I don't know where to start because I'm rare `sbt` user.

**Comment by thesamet** [comment]
Since it's not an official protoc plugin, it feels out-of-scope to me. There are many third-party protoc plugins - should we support them all? That means updating their versions, keeping up with their download URL changes, etc.

My preference would be to make it easier for users, though I'm not sure how much of the boilerplate you see in the example we can cut if we keep things generic.

One thing that is definitely missing is a protoc-bridge [Generator](https://github.com/scalapb/protoc-bridge/blob/master/src/main/scala/protocbridge/Generator.scala) that corresponds to an external protoc plugin that is on the local filesystem - a PR on this will be welcome. 

Then, there's a separate question on how we get some arbitrary file to the local filesystem, where to cache it - that seems like something that the user's build tool (sbt or whatever) should worry about.

**Comment by augi** [comment]
Thanks for your quick response!

I feel that gRPC plugin is more privileged than other plugins - this is why asked this question.

Actually, having support for simple use of a plugin would be more than sufficient. It's exactly how [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) works.
```gradle
protobuf {
  plugins {
    grpc {
      artifact = 'io.grpc:protoc-gen-grpc-java:1.0.0-pre2'
      // or
      // path = 'tools/protoc-gen-grpc-java'
    }
  }
}
```
This ensures that the _artifact_ is downloaded as regular Maven dependency using Gradle. So it stores the file to local Maven repository automatically.

So it would be nice if your library worked in similar way, so use the _plugin artifact_ as a new _compile-time_ dependency (I have no clue how difficult is it in sbt).
