### ISSUE TITLE
Generating proto files from multiple sbt projects

### ISSUE THREAD

**Issue by fgfernandez0321** [thesamet/sbt-protoc#73]
Hi,
I have a project with 3 sbt  projects inside and I want to generate proto classes based on the proto files defined in every project:

 - shopping-cart-service/cart-api/src/main/protobuf/cart.proto
 - shopping-cart-service/item-api/src/main/protobuf/item.proto
 - shopping-cart-service/price-api/src/main/protobuf/price.proto

When I compile the project, some classes are not generated, sometimes price and cart are generated inside cart project, sometimes cart is not generated. I uploaded a test project in order to provide you the environment where these issues happened. 

[shopping-cart-service.zip](https://github.com/thesamet/sbt-protoc/files/2229474/shopping-cart-service.zip)

Could you please help me?

Regards

**Comment by thesamet** [comment]
When I run `sbt`:

```
sbt:shopping-cart-service> protocTargets
[info] cart-api / Compile / protocTargets
[info] 	List(Target(JvmGenerator(scala,scalapb.ScalaPbCodeGenerator$@3ff53704),/tmp/shopping-cart-service/cart-api/target/scala-2.12/src_managed/main,List(grpc)))
[info] item-api / Compile / protocTargets
[info] 	List(Target(JvmGenerator(scala,scalapb.ScalaPbCodeGenerator$@3ff53704),/tmp/shopping-cart-service/item-api/target/scala-2.12/src_managed/main,List(grpc)))
[info] price-api / Compile / protocTargets
[info] 	List(Target(JvmGenerator(scala,scalapb.ScalaPbCodeGenerator$@3ff53704),/tmp/shopping-cart-service/cart-api/target/scala-2.12/src_managed/main,List(grpc)))
[info] Compile / protocTargets
[info] 	List(Target(JvmGenerator(scala,scalapb.ScalaPbCodeGenerator$@3ff53704),/tmp/shopping-cart-service/cart-api/target/scala-2.12/src_managed/main,List(grpc)))
```

This shows the PB.targets settings you have. See that the price-api project has the cart-api as the path to generate code to? 
If you go to the project-specific SBT files, you'll see that they have "in ThisBuild" scope that make them affect the gloval build and this is probably why this is happening.

You could remove the "in ThisBuild" from all the sbt files. A better option, since all these files are the same, would be to put the settings in `commonSettings` on the main build.sbt file:

```
def commonSettings: Seq[Setting[_]] = Seq(
	libraryDependencies ++= Seq(
		pb
	),
    PB.targets := Seq(
        scalapb.gen() -> (sourceManaged in Compile).value
    )
)
```

Hope this helps!
