### ISSUE TITLE
Error using ScalaPB on OpenBSD

### ISSUE THREAD

**Issue by jlncrnt** [thesamet/sbt-protoc#76]
Hi, 

I've developed an application on Fedora and I'm now trying to build it on OpenBSD (the target platform), but I get this error : 

`error occurred while compiling protobuf files: Unsupported platform: protoc-3.5.1-openbsd-x86_64.exe`

Is this supposed to happen ? If OpenBSD is really unsupported, is there a way to overwrite the `protoc` path somehow ?

Thank you

**Comment by ProbablyJody** [comment]
Was there a resolution here? I'm seeing a similar issue and would definitely like to know if you figured out the root cause.

**Comment by thesamet** [comment]
There's no official binary of protoc for OpenBSD. What you can do is to build [protoc](https://github.com/protocolbuffers/protobuf) on OpenBSD. Then use `PB.runProtoc in Compile` as [explained here](https://github.com/thesamet/sbt-protoc/) to tell sbt-protoc to run your custom built protoc instead of looking for a prebuilt one.
